<a href="https://colab.research.google.com/github/ashok-arora/ML-Zoomcamp/blob/main/homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Zoomcamp Homework #1](#https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/homework.md)

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-11 23:19:59--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.07s   

2021-09-11 23:20:00 (21.2 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('./data.csv')
print(df.head(), df.columns)

  Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns] Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')


## Answer 1

In [ ]:
print('Numpy version: {}'.format(np.__version__))

Numpy version: 1.19.5


## Answer 2

In [ ]:
print('Pandas version: {}'.format(pd.__version__))

Pandas version: 1.1.5


## Answer 3


In [ ]:
average_price_of_bmw_cars = df.groupby('Make')['MSRP'].mean()['BMW']
print('Average Price of BMW Cars: {}'.format(average_price_of_bmw_cars))

Average Price of BMW Cars: 61546.76347305389


## Answer 4

In [ ]:
cars_after_2015 = df.loc[df['Year'] >= 2015]
cars_after_2015_with_missing_engine_hp = cars_after_2015.isnull().sum()['Engine HP']
print('Number of cars made in 2015 or later with missing Engine HP value: {}'.format(cars_after_2015_with_missing_engine_hp))

Number of cars made in 2015 or later with missing Engine HP value: 51


## Answer 5

In [ ]:
print('Number of missing values for Engine HP: {}'.format(df['Engine HP'].isna().sum()))

new_df = df['Engine HP'].fillna(df['Engine HP'].mean())
print('Number of missing values for Engine HP after filling with mean: {}'.format(new_df.isna().sum()))

mean_hp_before = df['Engine HP'].mean()
mean_hp_after = new_df.mean()

print('Mean of Engine HP before filling with mean: {}'.format(round(mean_hp_before)))
print('Mean of Engine HP after filling with mean: {}'.format(round(mean_hp_after)))

Number of missing values for Engine HP: 69
Number of missing values for Engine HP after filling with mean: 0
Mean of Engine HP before filling with mean: 249
Mean of Engine HP after filling with mean: 249


## Answer 6

In [ ]:
new_df = df.loc[df['Make'] == 'Rolls-Royce']

new_df = new_df[['Engine HP', 'Engine Cylinders', 'highway MPG']]
print(new_df.drop_duplicates())

X = new_df.drop_duplicates().to_numpy()
print(X)

XTX = np.matmul(X.T,X)
print(XTX)

XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse.sum())

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21
[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]
[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]
0.032212320677486125


## Answer 7

In [ ]:
Y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
XTX_inverse_XT = np.matmul(XTX_inverse, X.T)
w = np.matmul(XTX_inverse_XT, Y)
print(w)

[ 0.19989598 31.02612262 31.65378877]
